"""Create pulses table

Revision ID: 07ce7ae63b4a
Revises: 
Create Date: 2026-01-19 17:30:20.366234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ce7ae63b4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='When this pulse should execute (UTC timestamp)'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='The instruction/context for Reeve when this pulse fires. This becomes the initial message in the Hapi session.'),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'NORMAL', 'LOW', 'DEFERRED', name='pulsepriority'), nullable=False, comment='Execution priority (determines order when multiple pulses are due)'),
    sa.Column('session_id', sa.String(length=500), nullable=True, comment='Optional Hapi session ID to resume existing context. If None, a new session is created.'),
    sa.Column('sticky_notes', sa.JSON(), nullable=True, comment="Optional list of reminder strings to inject into the prompt. Example: ['Check if user replied to ski trip', 'Follow up on PR review']"),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='pulsestatus'), nullable=False, comment='Current execution status of this pulse'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True, comment='When this pulse actually executed (may differ from scheduled_at)'),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True, comment='How long the Hapi session took to complete (milliseconds)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if status=FAILED. Used for debugging and retry logic.'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of times this pulse has been retried after failure'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum retry attempts before giving up'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When this pulse was created (for auditing)'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment="Who/what created this pulse. Examples: 'reeve', 'telegram_listener', 'user_cli'"),
    sa.Column('tags', sa.JSON(), nullable=True, comment="Optional tags for categorization/filtering. Example: ['hourly_check', 'calendar_sync', 'snowboarding']"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pulse_execution', 'pulses', ['status', 'scheduled_at', 'priority'], unique=False)
    op.create_index('idx_pulse_upcoming', 'pulses', ['scheduled_at', 'status'], unique=False)
    op.create_index(op.f('ix_pulses_priority'), 'pulses', ['priority'], unique=False)
    op.create_index(op.f('ix_pulses_scheduled_at'), 'pulses', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_pulses_status'), 'pulses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pulses_status'), table_name='pulses')
    op.drop_index(op.f('ix_pulses_scheduled_at'), table_name='pulses')
    op.drop_index(op.f('ix_pulses_priority'), table_name='pulses')
    op.drop_index('idx_pulse_upcoming', table_name='pulses')
    op.drop_index('idx_pulse_execution', table_name='pulses')
    op.drop_table('pulses')
    # ### end Alembic commands ###
